# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed827ecb707107a001e2e2f98c8a2e53174e6b4b38ed10ad842683a3e833315f33659d9c6e0d3d4c7e7a83cacd6cd53d3f26b49b75f3dc6101eeb5e5f1c36884

test:
  secret_key_base: 4e81e169c1fbe3359356e6af12f10e781bfc1b365fc98065732aac23bacea4828a53484926566570fe1715e90a169ec3e5254a65f7476f0c9946b06e64fa134d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
